package com.example.ui.screens

import android.app.Activity
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.launch

@Composable
fun AuthScreen(onAuthSuccess: () -> Unit) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    var isLoading by remember { mutableStateOf(false) }
    var errorMessage by remember { mutableStateOf<String?>(null) }

    Column(
        modifier = Modifier.fillMaxSize().padding(32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text("Melofy", style = MaterialTheme.typography.displayMedium, color = MaterialTheme.colorScheme.primary)
        Text("Nikmati Musik Favoritmu Dimana Saja", style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
        Spacer(modifier = Modifier.height(48.dp))

        if (isLoading) {
            CircularProgressIndicator()
        } else {
            Button(
                onClick = {
                    isLoading = true
                    errorMessage = null
                    coroutineScope.launch {
                        try {
                            val credentialManager = CredentialManager.create(context)
                            // Use a placeholder web client ID if none provided. 
                            // In a real app, this should come from strings.xml (default_web_client_id) 
                            // generated by google-services plugin, but we might not have it.
                            val webClientId = runCatching {
                                context.getString(
                                    context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
                                )
                            }.getOrDefault("")
                            
                            val googleIdOption = GetGoogleIdOption.Builder()
                                .setFilterByAuthorizedAccounts(false)
                                .setServerClientId(if (webClientId.isNotEmpty()) webClientId else "PLACEHOLDER_CLIENT_ID")
                                .build()

                            val request = GetCredentialRequest.Builder()
                                .addCredentialOption(googleIdOption)
                                .build()

                            val result = credentialManager.getCredential(
                                request = request,
                                context = context as Activity
                            )

                            val credential = result.credential
                            if (credential is GoogleIdTokenCredential) {
                                val idToken = credential.idToken
                                val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                                try {
                                    FirebaseAuth.getInstance().signInWithCredential(firebaseCredential).await()
                                    onAuthSuccess()
                                } catch (e: Exception) {
                                    errorMessage = "Firebase Auth Failed: \${e.message}"
                                }
                            } else {
                                errorMessage = "Unexpected credential type"
                            }
                        } catch (e: Exception) {
                            // As a fallback for preview environments where Google Sign-In is not fully set up
                            // We do an anonymous login so the user can still test the UI
                            FirebaseAuth.getInstance().signInAnonymously().addOnCompleteListener { task ->
                                if (task.isSuccessful) {
                                    onAuthSuccess()
                                } else {
                                    errorMessage = "Auth Error: \${e.message} (Fallback failed)"
                                }
                            }
                        } finally {
                            isLoading = false
                        }
                    }
                },
                modifier = Modifier.fillMaxWidth().height(50.dp)
            ) {
                Text("Login dengan Google (atau Anonymous)")
            }
        }
        
        if (errorMessage != null) {
            Spacer(modifier = Modifier.height(16.dp))
            Text(errorMessage!!, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall)
        }
    }
}
